/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * Dang! — Agentic SOC Pipeline: Canonical Schema Contracts
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * These three schemas are the load-bearing contracts for the entire agentic
 * pipeline. Every agent stage consumes and produces one of these objects.
 * If these are stable, the rest is composable.
 *
 * Contract 1: TriageObject     — the canonical alert handoff
 * Contract 2: CorrelationBundle — the canonical evidence synthesis handoff
 * Contract 3: LivingCaseObject — the canonical investigation state
 *
 * Design principles:
 * - Fresh context per stage, structured JSON handoff between stages
 * - Evidence, inference, and uncertainty are always separated
 * - All timestamps are UTC ISO-8601 strings
 * - All IDs preserve their original Wazuh format (never normalized away)
 * - Confidence scores are 0.0–1.0 floats
 * - Every field that came from the LLM is marked with provenance
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// ── Shared Primitives ──────────────────────────────────────────────────────────

/** Severity levels aligned with Wazuh rule levels and SOC conventions */
export type AgenticSeverity = "critical" | "high" | "medium" | "low" | "info";

/** Confidence score: 0.0 (no confidence) to 1.0 (certain) */
export type Confidence = number;

/** Route recommendation from triage — determines downstream pipeline path */
export type TriageRoute =
  | "A_DUPLICATE_NOISY"      // Dedup logic → suppression/tuning → analyst confirm
  | "B_LOW_CONFIDENCE"       // Enrichment → correlation → analyst review queue
  | "C_HIGH_CONFIDENCE"      // Immediate correlation → investigation → response → approval gate
  | "D_LIKELY_BENIGN";       // Closure draft → analyst validation → tuning candidate

/** Provenance marker: where did this data come from? */
export type ProvenanceSource =
  | "wazuh_alert"            // Raw Wazuh alert field
  | "wazuh_agent"            // Wazuh agent metadata
  | "wazuh_vuln"             // Wazuh vulnerability scan
  | "wazuh_fim"              // Wazuh FIM event
  | "wazuh_sca"              // Wazuh SCA policy check
  | "threat_intel"           // OTX or other threat intel feed
  | "llm_inference"          // Generated by the LLM (not raw telemetry)
  | "analyst_input"          // Manually entered by analyst
  | "system_computed";       // Computed by deterministic backend logic

/** A single extracted entity with provenance */
export interface ExtractedEntity {
  type: "host" | "user" | "process" | "hash" | "ip" | "domain" | "rule_id" | "mitre_technique" | "cve" | "file_path" | "port" | "registry_key";
  value: string;
  /** Where this entity was extracted from */
  source: ProvenanceSource;
  /** Confidence that this extraction is correct (0.0–1.0) */
  confidence: Confidence;
  /** Additional context (e.g., hash type, IP version, process path) */
  metadata?: Record<string, unknown>;
}

/** A piece of evidence with explicit provenance */
export interface EvidenceItem {
  /** Unique identifier for this evidence item */
  id: string;
  /** Human-readable label */
  label: string;
  /** What kind of evidence is this? */
  type: "alert" | "vulnerability" | "fim_event" | "sca_result" | "agent_metadata" | "threat_intel" | "analyst_note" | "network_event" | "process_event";
  /** Where this evidence came from */
  source: ProvenanceSource;
  /** The actual data — preserved as-is from the source */
  data: Record<string, unknown>;
  /** When this evidence was collected (UTC ISO-8601) */
  collectedAt: string;
  /** Relevance score to the current context (0.0–1.0) */
  relevance?: Confidence;
}

/** An uncertainty — something the system doesn't know and the analyst should */
export interface Uncertainty {
  /** What is unknown */
  description: string;
  /** Why it matters */
  impact: string;
  /** How the analyst could resolve it */
  suggestedAction?: string;
}

/** MITRE ATT&CK mapping with confidence */
export interface MitreMapping {
  techniqueId: string;       // e.g., "T1059.001"
  techniqueName: string;     // e.g., "PowerShell"
  tactic: string;            // e.g., "Execution"
  confidence: Confidence;
  source: ProvenanceSource;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CONTRACT 1: TRIAGE OBJECT
// The canonical alert handoff. Everything downstream consumes this.
// ═══════════════════════════════════════════════════════════════════════════════

export interface TriageObject {
  /** Schema version for forward compatibility */
  schemaVersion: "1.0";

  /** Unique triage ID (generated by the system) */
  triageId: string;

  /** UTC ISO-8601 timestamp when triage was performed */
  triagedAt: string;

  /** Who/what performed this triage */
  triagedBy: "triage_agent" | "analyst_manual";

  // ── Alert Identity ─────────────────────────────────────────────────────────

  /** Original Wazuh alert ID (preserved verbatim) */
  alertId: string;

  /** Wazuh rule ID that fired */
  ruleId: string;

  /** Wazuh rule description */
  ruleDescription: string;

  /** Original Wazuh rule level (0–15) */
  ruleLevel: number;

  /** Alert timestamp from Wazuh (preserved verbatim, UTC ISO-8601) */
  alertTimestamp: string;

  /** Agent that generated this alert */
  agent: {
    id: string;
    name: string;
    ip?: string;
    os?: string;
    groups?: string[];
  };

  // ── Normalized Classification ──────────────────────────────────────────────

  /** Normalized alert type/family (e.g., "brute_force", "malware_execution", "policy_violation") */
  alertFamily: string;

  /** AI-assigned severity (may differ from ruleLevel) */
  severity: AgenticSeverity;

  /** Confidence in the severity assignment */
  severityConfidence: Confidence;

  /** Brief evidence-backed reasoning for the severity */
  severityReasoning: string;

  // ── Entity Extraction ──────────────────────────────────────────────────────

  /** All entities extracted from this alert */
  entities: ExtractedEntity[];

  // ── MITRE ATT&CK ──────────────────────────────────────────────────────────

  /** MITRE technique mappings (from Wazuh + LLM inference) */
  mitreMapping: MitreMapping[];

  // ── Deduplication ──────────────────────────────────────────────────────────

  /** Dedup/similarity assessment */
  dedup: {
    /** Is this a likely duplicate of a recent alert? */
    isDuplicate: boolean;
    /** Similarity score to the closest recent alert (0.0–1.0) */
    similarityScore: Confidence;
    /** ID of the most similar recent triage object, if any */
    similarTriageId?: string;
    /** Brief explanation of why it's similar or unique */
    reasoning: string;
  };

  // ── Route Recommendation ───────────────────────────────────────────────────

  /** Recommended pipeline route */
  route: TriageRoute;

  /** Why this route was chosen */
  routeReasoning: string;

  // ── Evidence Summary ───────────────────────────────────────────────────────

  /** Concise, analyst-readable summary of the alert (2–4 sentences) */
  summary: string;

  /** Key evidence items that informed the triage */
  keyEvidence: EvidenceItem[];

  // ── Uncertainties ──────────────────────────────────────────────────────────

  /** Things the triage agent doesn't know */
  uncertainties: Uncertainty[];

  // ── Case Link ──────────────────────────────────────────────────────────────

  /** Suggestion for linking to an existing investigation */
  caseLink: {
    /** Should this alert be linked to an existing case? */
    shouldLink: boolean;
    /** Suggested investigation session ID, if any */
    suggestedCaseId?: number;
    /** Suggested case title, if any */
    suggestedCaseTitle?: string;
    /** Confidence in the case link suggestion */
    confidence: Confidence;
    /** Reasoning for the suggestion */
    reasoning: string;
  };

  // ── Raw Data ───────────────────────────────────────────────────────────────

  /** Original raw alert JSON (preserved verbatim for forensic integrity) */
  rawAlert: Record<string, unknown>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CONTRACT 2: CORRELATION BUNDLE
// The canonical evidence synthesis handoff. Produced by the Correlation Agent.
// ═══════════════════════════════════════════════════════════════════════════════

export interface CorrelationBundle {
  /** Schema version for forward compatibility */
  schemaVersion: "1.0";

  /** Unique correlation ID */
  correlationId: string;

  /** UTC ISO-8601 timestamp when correlation was performed */
  correlatedAt: string;

  /** The triage object that triggered this correlation */
  sourceTriageId: string;

  // ── Related Alerts ─────────────────────────────────────────────────────────

  /** Alerts related by shared entities (same host, user, IP, hash, etc.) */
  relatedAlerts: Array<{
    alertId: string;
    ruleId: string;
    ruleDescription: string;
    ruleLevel: number;
    timestamp: string;
    agentId: string;
    /** Which entity linked this alert to the source */
    linkedBy: ExtractedEntity;
    /** How strong is the relationship (0.0–1.0) */
    relevance: Confidence;
  }>;

  // ── Related Entities ───────────────────────────────────────────────────────

  /** Entities discovered during correlation that weren't in the original alert */
  discoveredEntities: ExtractedEntity[];

  // ── Vulnerability Context ──────────────────────────────────────────────────

  /** Vulnerabilities on the affected host(s) that may be relevant */
  vulnerabilityContext: Array<{
    cveId: string;
    severity: AgenticSeverity;
    name: string;
    affectedPackage?: string;
    /** How relevant is this vuln to the alert (0.0–1.0) */
    relevance: Confidence;
  }>;

  // ── FIM Context ────────────────────────────────────────────────────────────

  /** Recent file integrity changes on the affected host(s) */
  fimContext: Array<{
    path: string;
    event: string;
    timestamp: string;
    relevance: Confidence;
  }>;

  // ── Threat Intel ───────────────────────────────────────────────────────────

  /** Threat intelligence matches for extracted IOCs */
  threatIntelMatches: Array<{
    ioc: string;
    iocType: string;
    source: string;
    threatName?: string;
    confidence: Confidence;
  }>;

  // ── Prior Investigations ───────────────────────────────────────────────────

  /** Existing investigations that may be related */
  priorInvestigations: Array<{
    investigationId: number;
    title: string;
    status: string;
    /** Why this investigation is related */
    linkReason: string;
    relevance: Confidence;
  }>;

  // ── Blast Radius ───────────────────────────────────────────────────────────

  /** Estimated scope of impact */
  blastRadius: {
    /** Number of hosts potentially affected */
    affectedHosts: number;
    /** Number of users potentially affected */
    affectedUsers: number;
    /** List of affected agent IDs */
    affectedAgentIds: string[];
    /** Asset criticality of affected systems */
    assetCriticality: "critical" | "high" | "medium" | "low" | "unknown";
    /** Confidence in the blast radius estimate */
    confidence: Confidence;
  };

  // ── Campaign Grouping ──────────────────────────────────────────────────────

  /** Assessment of whether this is part of a larger campaign */
  campaignAssessment: {
    /** Does this look like part of a coordinated campaign? */
    likelyCampaign: boolean;
    /** Suggested campaign name/label if applicable */
    campaignLabel?: string;
    /** MITRE techniques that cluster together */
    clusteredTechniques: MitreMapping[];
    /** Confidence in the campaign assessment */
    confidence: Confidence;
    reasoning: string;
  };

  // ── Merge/New Case ─────────────────────────────────────────────────────────

  /** Should this be merged into an existing case or create a new one? */
  caseRecommendation: {
    action: "merge_existing" | "create_new" | "defer_to_analyst";
    /** If merge, which case? */
    mergeTargetId?: number;
    mergeTargetTitle?: string;
    /** Confidence in the recommendation */
    confidence: Confidence;
    reasoning: string;
  };

  // ── Synthesis ──────────────────────────────────────────────────────────────

  /** LLM-generated synthesis of all correlated evidence */
  synthesis: {
    /** Narrative summary of the correlation findings (3–6 sentences) */
    narrative: string;
    /** What evidence supports concern */
    supportingEvidence: EvidenceItem[];
    /** What evidence argues against concern */
    conflictingEvidence: EvidenceItem[];
    /** What's still missing */
    missingEvidence: Uncertainty[];
    /** Overall correlation confidence */
    confidence: Confidence;
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// CONTRACT 3: LIVING CASE OBJECT
// The canonical investigation state. Updated incrementally by the Case Agent.
// ═══════════════════════════════════════════════════════════════════════════════

export interface LivingCaseObject {
  /** Schema version for forward compatibility */
  schemaVersion: "1.0";

  /** Investigation session ID (maps to investigation_sessions.id) */
  caseId: number;

  /** Last updated timestamp (UTC ISO-8601) */
  lastUpdatedAt: string;

  /** Who last updated this case state */
  lastUpdatedBy: "case_agent" | "hypothesis_agent" | "response_agent" | "analyst_manual";

  // ── Working Theory ─────────────────────────────────────────────────────────

  /** Current best explanation for what happened */
  workingTheory: {
    /** The theory statement */
    statement: string;
    /** Confidence in this theory */
    confidence: Confidence;
    /** Evidence supporting this theory */
    supportingEvidence: string[];
    /** Evidence conflicting with this theory */
    conflictingEvidence: string[];
  };

  /** Alternative explanations the analyst should consider */
  alternateTheories: Array<{
    statement: string;
    confidence: Confidence;
    supportingEvidence: string[];
    /** Why this is less likely than the working theory */
    whyLessLikely: string;
  }>;

  // ── Pivots & Gaps ──────────────────────────────────────────────────────────

  /** Investigative actions that have been completed */
  completedPivots: Array<{
    /** What was done */
    action: string;
    /** When it was done (UTC ISO-8601) */
    performedAt: string;
    /** Who did it */
    performedBy: string;
    /** What was found */
    finding: string;
    /** Did this change the working theory? */
    impactedTheory: boolean;
  }>;

  /** Evidence gaps that still need to be filled */
  evidenceGaps: Array<{
    /** What is missing */
    description: string;
    /** Why it matters */
    impact: string;
    /** Suggested action to fill the gap */
    suggestedAction: string;
    /** Priority of filling this gap */
    priority: "critical" | "high" | "medium" | "low";
  }>;

  /** Suggested next investigative steps */
  suggestedNextSteps: Array<{
    /** What to do */
    action: string;
    /** Why this is recommended */
    rationale: string;
    /** Priority */
    priority: "critical" | "high" | "medium" | "low";
    /** Estimated effort */
    effort: "quick" | "moderate" | "deep_dive";
  }>;

  // ── Response Recommendations ───────────────────────────────────────────────

  /** Recommended response actions, grouped by urgency */
  recommendedActions: Array<{
    /** What to do */
    action: string;
    /** Category */
    category: "immediate" | "next" | "optional";
    /** Does this require human approval? */
    requiresApproval: boolean;
    /** Evidence that supports this recommendation */
    evidenceBasis: string[];
    /** Linked playbook, if any */
    playbookRef?: string;
    /** Current state of this recommendation */
    state: "proposed" | "approved" | "rejected" | "executed" | "deferred";
    /** Analyst who approved/rejected, if applicable */
    decidedBy?: string;
    /** When the decision was made */
    decidedAt?: string;
  }>;

  // ── Timeline Summary ───────────────────────────────────────────────────────

  /** Chronological summary of significant events in this case */
  timelineSummary: Array<{
    /** When (UTC ISO-8601) */
    timestamp: string;
    /** What happened */
    event: string;
    /** Source of this timeline entry */
    source: ProvenanceSource;
    /** Significance to the investigation */
    significance: "critical" | "high" | "medium" | "low";
  }>;

  // ── Linked Artifacts ───────────────────────────────────────────────────────

  /** Alert IDs linked to this case */
  linkedAlertIds: string[];

  /** Triage object IDs that fed into this case */
  linkedTriageIds: string[];

  /** Correlation bundle IDs that fed into this case */
  linkedCorrelationIds: string[];

  /** All entities involved in this case */
  linkedEntities: ExtractedEntity[];

  // ── Documentation Readiness ────────────────────────────────────────────────

  /** Pre-drafted documentation artifacts (editable by analyst) */
  draftDocumentation: {
    /** Case summary for shift handoff */
    shiftHandoff?: string;
    /** Escalation summary for management */
    escalationSummary?: string;
    /** Closure rationale */
    closureRationale?: string;
    /** Executive summary (non-technical) */
    executiveSummary?: string;
    /** Detection tuning suggestions */
    tuningSuggestions?: string;
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// PIPELINE STAGE CONTRACTS
// Define what each agent receives and returns
// ═══════════════════════════════════════════════════════════════════════════════

/** Input to the Triage Agent */
export interface TriageAgentInput {
  /** Raw Wazuh alert JSON */
  rawAlert: Record<string, unknown>;
  /** Agent metadata (if available) */
  agentContext?: {
    id: string;
    name: string;
    ip?: string;
    os?: string;
    groups?: string[];
  };
  /** Recent triage objects for dedup comparison (last N from same agent/rule) */
  recentTriageObjects?: Array<{
    triageId: string;
    alertFamily: string;
    ruleId: string;
    severity: AgenticSeverity;
    triagedAt: string;
    summary: string;
  }>;
  /** Active investigation sessions for case-link suggestion */
  activeInvestigations?: Array<{
    id: number;
    title: string;
    description?: string;
    linkedEntities?: string[];
  }>;
}

/** Input to the Correlation Agent */
export interface CorrelationAgentInput {
  /** The triage object to correlate */
  triageObject: TriageObject;
  /** Retrieved evidence pack (assembled by backend, not the LLM) */
  evidencePack: {
    sameHostAlerts: Array<Record<string, unknown>>;
    sameUserAlerts: Array<Record<string, unknown>>;
    sameIocAlerts: Array<Record<string, unknown>>;
    hostVulnerabilities: Array<Record<string, unknown>>;
    hostFimEvents: Array<Record<string, unknown>>;
    threatIntelHits: Array<Record<string, unknown>>;
    priorInvestigations: Array<{ id: number; title: string; status: string; evidence: unknown[] }>;
  };
}

/** Input to the Hypothesis Agent */
export interface HypothesisAgentInput {
  /** The triage object */
  triageObject: TriageObject;
  /** The correlation bundle */
  correlationBundle: CorrelationBundle;
}

/** Input to the Case Agent (incremental update) */
export interface CaseAgentInput {
  /** Current living case state (or null for new case) */
  currentCase: LivingCaseObject | null;
  /** New triage object being added to the case */
  newTriage?: TriageObject;
  /** New correlation bundle being added */
  newCorrelation?: CorrelationBundle;
  /** Analyst action to record */
  analystAction?: {
    type: "pivot_completed" | "theory_override" | "action_approved" | "action_rejected" | "note_added";
    details: Record<string, unknown>;
  };
}
